name: Build and Release fastokens

on:
  push:
    branches:
      - main
      - master
    paths:
      - "python/**"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"
    tags:
      - "*"
  pull_request:
    paths:
      - "python/**"
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      publish_pypi:
        description: "Publish to PyPI?"
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build-package:
    uses: ./.github/workflows/build-maturin.yml
    with:
      publish_pypi: ${{ github.event_name == 'workflow_dispatch' && fromJSON(github.event.inputs.publish_pypi) }}
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
